---
# Source: gitlab/charts/redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis-master
  namespace: "default"
  labels:
    app: redis
    chart: redis-11.3.4
    release: gitlab
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: gitlab
    role: master
